### PR TITLE
Autopurchasing option added

### PR DESCRIPTION
**Pull request by tangerinehuge**
I created a new script for chrome based on the existing chrome script. It checks to see if you're on the correct page and then starts looking for available slots, refreshing at the interval specified in the config file. If it finds open slots it selects the first available one and completes the purchase. It also optionally notifies you via Slack, SMS, or IFTTT.

### CODE REVIEW

**Comment by canturkisci** [comment]
@tangerinehuge I am planning to test our your branch. Can you please give me some guidance?
- It seems your new pieces are on Python3. Should I run the code on Python3?
- For slack/ifttt, is there any special set up/integration needed? Can i just use my existing accounts?

Thanks!

**Comment by tangerinehuge** [comment]
I think it will probably run on 2.7 but I only tested it on 3. I would just run it on 3 at this point since everyone should have it on their systems by now. It looks like the other scripts should run on 3 as well since they use the new print syntax.

The slack/ifttt instructions are linked in the example config file. You just need to setup webhooks in your existing accounts, enable those notifications in the config file and fill in the necessary values. There are placeholders for them in the file. Let me know if you have more questions.

Cheers!

**Comment by canturkisci** [comment]
Thanks. This gets me going! 👍

**Comment by pcomputo** [comment]
Testing this is going to take me a while. Have you tested this on all three OS platforms?

**Comment by tangerinehuge** [comment]
I've only tested it on Mac but I'd imagine it should be pretty easy to port to the other platforms since it uses the selenium module. I stripped out the beautifulsoup module since it wasn't necessary.

**Comment by bobbymcshane** [comment]
I'm trying to run your fork on my machine but I keep failing with:

```
No slots found, waiting 4 seconds...refreshing.
Traceback (most recent call last):
  File "whole_foods_delivery_slot_chrome_autobuy.py", line 126, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "whole_foods_delivery_slot_chrome_autobuy.py", line 69, in getWFSlot
    slot_button.click()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-pressed="false" class="a-button-text ufss-slot-toggle-native-button" type="button">...</button> is not clickable at point (624, 673). Other element would receive the click: <div id="first-pipeline-load-page-spinner-blocker"></div>
```

I've tried playing around with it but haven't been successful in working around the issue. I've never used Selenium before and can't easily iterate on this because delivery slots are so hard to come by

**Comment by tangerinehuge** [comment]
Ah, I'm actually glad you hit that because I hit that one as well but assumed I must have moved or resized the window while the script was running. I'll see if I can track down the cause. I was able to run the script successfully so it seems to be an intermittent issue. I'm wondering if it has to do with which days the slots are available.

**Comment by smessmer** [comment]
Crashes for me with 

```
Traceback (most recent call last):
  File "whole_foods_delivery_slot_chrome_autobuy.py", line 126, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "whole_foods_delivery_slot_chrome_autobuy.py", line 69, in getWFSlot
    slot_button.click()
  File "/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-pressed="false" class="a-button-text ufss-slot-toggle-native-button" type="button">...</button> is not clickable at point (615, 672). Other element would receive the click: <div id="first-pipeline-load-page-spinner-blocker"></div>
  (Session info: chrome=80.0.3987.163)
```

**Comment by tangerinehuge** [comment]
Closing this pull request while we debug the ElementClickInterceptedException

**Comment by bobbymcshane** [comment]
Thank you!

**Comment by bobbymcshane** [comment]
> Ah, I'm actually glad you hit that because I hit that one as well but assumed I must have moved or resized the window while the script was running. I'll see if I can track down the cause. I was able to run the script successfully so it seems to be an intermittent issue. I'm wondering if it has to do with which days the slots are available.

Let me know if you need me to try out any changes :)

**Comment by robber-m** [comment]
Update: It finally worked for me! Autopurchasing is really a key feature :) it's otherwise nearly impossible to get a delivery slot in my Brooklyn Neighborhood right now.

**Comment by tangerinehuge** [comment]
I found the bug. Selenium wasn't waiting long enough for the spinner to disappear before clicking the button. I changed the code to wait for the button to become clickable before it actually calls the click() method.

**Comment by tangerinehuge** [comment]
New pull request here: https://github.com/pcomputo/Whole-Foods-Delivery-Slot/pull/22

**Pull request closed without merging**
