### PR TITLE
Switched whole_foods_delivery_slot_chrome.py to use cross-platform TTS pyttsx3

### PR DESCRIPTION
**Pull request by Stormwind99**
.. so  TTS works under Windows, Mac, other platforms without modifications (assuming supported TTS system is installed)

### CODE REVIEW

**Comment by mp42244** [comment]
What does this change do ?

**Comment by Stormwind99** [comment]
Since `os.system('say "Slots for delivery opened!"')` doesn't work under Windows and other platforms, this change switches whole_foods_delivery_slot_chrome.py to use cross-platform TTS pyttsx3 module instead `os.system('say "text"')` so TTS (text-to-speech) works under multiple platforms without modifications (assuming supported TTS system is installed).

**Comment by jason123santa** [comment]
I fixed it for 1-2 day here https://github.com/jason123santa/Whole-Foods-Delivery-Slot

**Comment by Stormwind99** [comment]
I merged it into my pyttsx3-using fork (and also merged from latest upstream) here: https://github.com/Stormwind99/Whole-Foods-Delivery-Slot

**Pull request closed without merging**
